import { EquipmentPicker, TrackingFields } from './ManageData'
import { exerciseName } from './exerciseLibrary'
import { useState } from 'react'
import { modes, uid, exerciseSchema, type Exercise, type Program, type Session } from './domain'
import { hasEntries } from './workoutEditing'
export default function ExerciseSwap({original,programs,disabled,onSave,onCancel}:{original:Session['exercises'][number];programs:Program[];disabled:boolean;onSave:(e:Exercise)=>Promise<boolean>;onCancel:()=>void}) {
 const options=programs.flatMap(p=>p.days.flatMap(d=>d.exercises.map(e=>({key:`${p.id}/${d.id}/${e.id}`,label:`${exerciseName(e)} · ${e.equipment} · ${d.name}`,exercise:e}))))
 const [chosen,setChosen]=useState(''),[draft,setDraft]=useState<Exercise>(()=>({id:uid(),variantId:uid(),equipmentId:uid(),name:'',equipment:'',mode:'Unspecified',sets:original.sets,target:original.target,rest:original.rest})),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const patch=(p:Partial<Exercise>)=>setDraft(old=>({...old,...p}))
 return <form className="swap-editor" onSubmit={async event=>{event.preventDefault();setError('');setSaving(true);try {const selected=chosen?options.find(o=>o.key===chosen)?.exercise:draft;if(!selected)throw new Error('Выберите упражнение заново.');const valid=exerciseSchema.safeParse(selected);if(!valid.success)throw new Error('Укажите название, оборудование и число подходов от 1 до 30.');if(await onSave(valid.data))onCancel()}catch(e){setError(e instanceof Error?e.message:'Не удалось заменить упражнение.')}finally{setSaving(false)}}}>
 <h3>Замена на сегодня</h3><p>{hasEntries(original)?'В упражнении уже есть записи. Они сохранятся, а замена появится следующим упражнением с пустыми подходами.':'Замена займёт место этого упражнения. Программа и прошлые тренировки сохранятся.'}</p>
 <fieldset disabled={disabled||saving}><label>Выбрать упражнение<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Новое упражнение</option>{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label>
 {!chosen&&<div className="form-grid"><label>Название замены<input required maxLength={2000} value={draft.name} onChange={e=>patch({name:e.target.value})}/></label><label>Оборудование замены<input required maxLength={2000} value={draft.equipment} onChange={e=>patch({equipment:e.target.value,equipmentId:uid(),stepGrams:null,availableGrams:[]})}/></label><label>Учёт веса замены<select value={draft.mode} onChange={e=>patch({mode:e.target.value as Exercise['mode'],equipmentId:uid(),stepGrams:null,availableGrams:[]})}>{Object.entries(modes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><EquipmentPicker exercise={draft} onChange={patch}/><TrackingFields exercise={draft} onChange={patch}/><label>Подходов в замене<input required type="number" inputMode="numeric" min="1" max="30" value={draft.sets} onChange={e=>patch({sets:Number(e.target.value)})}/></label><label>Цель замены<input maxLength={2000} value={draft.target} onChange={e=>patch({target:e.target.value})}/></label><label>Отдых в замене, секунд<input type="number" inputMode="numeric" min="0" max="1800" value={draft.rest??''} onChange={e=>patch({rest:e.target.value===''?null:Number(e.target.value)})}/></label></div>}
 {chosen&&<p>Будут использованы подходы и профиль веса выбранного упражнения. Веса и результаты не переносятся.</p>}
 {error&&<p role="alert">{error}</p>}<div className="actions"><button className="primary">{hasEntries(original)?'Добавить замену рядом':'Применить замену'}</button><button type="button" onClick={onCancel}>Отмена замены</button></div></fieldset></form>
}
