import { test, expect } from '@playwright/test'
import { openExercise, selectSet, startDay } from './helpers'

test('beloved program is available alongside the other seeds, survives reload and logs both sides', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/training/')
  await page.getByRole('button', { name: 'Добавить Bro Split в дневник', exact: true }).click()
  await page.getByRole('button', { name: 'Программы', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить личный шаблон А/Б', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить «Для Любименькой ❤️»', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Для Любименькой ❤️', exact: true })).toBeVisible()
  await expect(page.getByText('Все готовые программы уже в дневнике.', { exact: true })).toBeVisible()
  await expect(page.locator('.program-exercise-list')).toHaveCount(3)
  await expect(page.locator('.program-exercise-list').last().getByText('Dead bug', { exact: true })).toBeVisible()
  await page.getByText('Заметки программы', { exact: true }).click()
  await expect(page.locator('.program-note')).toContainText('Двойная прогрессия')
  await page.getByText('Заметки программы', { exact: true }).click()
  await page.screenshot({ path: info.outputPath('beloved-program.png'), fullPage: true })
  await page.getByRole('button', { name: 'Сегодня', exact: true }).click()
  const select = page.getByLabel('Текущая программа')
  await expect(select.locator('option')).toHaveCount(3)
  await expect(select).toHaveValue('be180926-0001-4000-8000-000000000001')
  await page.reload()
  await expect(select).toHaveValue('be180926-0001-4000-8000-000000000001')
  await startDay(page, /Руки \+ корпус.*6 упражнений/)
  await openExercise(page, 'Dead bug')
  await expect(page.getByLabel('Вес подхода 1', { exact: true })).toHaveCount(0)
  await page.getByLabel('Повторения подхода 1', { exact: true }).fill('8')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Обзор тренировки', exact: true })).toContainText('1 из 26 подходов выполнено')
  await selectSet(page, 'Dead bug', 1)
  await expect(page.getByLabel('Повторения подхода 2', { exact: true })).toHaveValue('')
  await page.getByLabel('Повторения подхода 2', { exact: true }).fill('9')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Обзор тренировки', exact: true })).toContainText('2 из 26 подходов выполнено')
  await selectSet(page, 'Dead bug', 2)
  await expect(page.getByLabel('Повторения подхода 3', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Повторения подхода 3', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Обзор тренировки', exact: true }).click()
  const core = page.locator('.workout-overview section').filter({ has: page.getByRole('heading', { name: 'Dead bug', exact: true }) })
  await expect(core.getByRole('button').nth(0)).toContainText('Левая')
  await expect(core.getByRole('button').nth(0)).toContainText('8')
  await expect(core.getByRole('button').nth(0)).toHaveClass(/completed/)
  await expect(core.getByRole('button').nth(1)).toContainText('Правая')
  await expect(core.getByRole('button').nth(1)).toContainText('9')
  await expect(core.getByRole('button').nth(1)).toHaveClass(/completed/)
  await page.screenshot({ path: info.outputPath('beloved-core.png'), fullPage: true })
  expect(errors).toEqual([])
})
