import { test, expect } from '@playwright/test'
import { editAllExercises, editExercise, finishWorkout, goTab, openProgramEditor, selectSet, startDay } from './helpers'

test('equipment, duration and sides persist; rest calendar and trash fit mobile',async({page},info)=>{
 await page.goto('/training/');await page.getByRole('button',{name:'Настройки',exact:true}).click()
 await page.getByRole('button',{name:'Оборудование',exact:true}).click()
 await page.getByLabel('Название оборудования',{exact:true}).fill('Тестовый блок')
 await page.getByRole('combobox',{name:'Учёт веса',exact:true}).selectOption('MachineStack')
 await page.getByLabel('Шаг веса, кг',{exact:true}).fill('7')
 await page.getByLabel('Доступные веса, кг, через ;',{exact:true}).fill('40;47;54')
 await page.getByRole('button',{name:'Добавить оборудование',exact:true}).click()
 await expect(page.locator('.manage-row').filter({hasText:'Тестовый блок'}).first()).toBeVisible()
 // Отдых планируется в календаре истории: в настройках этого раздела больше нет.
 await goTab(page,'История');await page.getByRole('button',{name:'Календарь',exact:true}).click()
 const rest=new Date();rest.setDate(rest.getDate()===15?16:15)
 const restDay=rest.toLocaleDateString('ru-RU',{day:'numeric',month:'long'})
 await page.getByRole('button',{name:`${restDay} · нет записей`,exact:true}).click()
 await page.getByRole('button',{name:'Запланировать отдых',exact:true}).click()
 await page.getByRole('button',{name:`${restDay} · отдых запланирован`,exact:true}).click()
 await page.getByRole('button',{name:'Отметить отдых',exact:true}).click()
 await expect(page.getByRole('button',{name:`${restDay} · отдых отмечен`,exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await openProgramEditor(page)
 await page.getByLabel('Название дня',{exact:true}).fill('Тест секунд')
 await page.getByLabel('Название и вариант').fill('Удержание на блоке')
 await editExercise(page,0)
 await page.getByLabel('Из каталога оборудования').selectOption({label:'Тестовый блок · Стек тренажёра'})
 await page.getByLabel('Что записывать').selectOption('duration')
 await page.getByRole('combobox',{name:'Стороны',exact:true}).selectOption('separate')
 await page.getByLabel('Рабочие подходы').fill('1')
 await page.getByRole('button',{name:'Сохранить программу'}).click()
 await expect(page.getByRole('button',{name:'Изменить программу',exact:true})).toBeVisible()
 await goTab(page,'Сегодня');await startDay(page,/Тест секунд/)
 await expect(page.locator('.set-wrap')).toHaveCount(1)
 await expect(page.getByRole('combobox',{name:'Сторона подхода 1',exact:true})).toHaveValue('left')
 await page.getByLabel('Вес подхода 1',{exact:true}).fill('40');await page.getByRole('button',{name:'+ Вес',exact:true}).click()
 await expect(page.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('47')
 await page.getByLabel('Секунды подхода 1',{exact:true}).fill('45');await page.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.getByRole('combobox',{name:'Сторона подхода 2',exact:true})).toHaveValue('right')
 await page.getByLabel('Вес подхода 2',{exact:true}).fill('47');await page.getByLabel('Секунды подхода 2',{exact:true}).fill('30');await page.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.getByText('Все подходы записаны',{exact:true})).toBeVisible()
 await selectSet(page,'Удержание на блоке',0)
 await page.reload();await expect(page.getByLabel('Секунды подхода 1',{exact:true})).toHaveValue('45')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:info.outputPath('duration-sides-mobile.png'),fullPage:true})
 await finishWorkout(page)
 await goTab(page,'Прогресс');await expect(page.locator('.progress-stats')).toContainText('45 сек')
 await page.getByLabel('Сторона для сравнения').selectOption('right');await expect(page.locator('.progress-stats')).toContainText('30 сек')
 await page.getByRole('button',{name:'Открыть тренировку',exact:true}).first().click()
 await page.getByRole('button',{name:'Исправить подход',exact:true}).nth(1).click()
 await page.locator('.correction-set[open]').getByLabel('Секунды',{exact:true}).fill('35');await page.getByRole('button',{name:'Сохранить исправления'}).click()
 await expect(page.getByRole('heading',{name:'Исправление записи'})).toHaveCount(0)
 await page.getByRole('button',{name:'В архив',exact:true}).click()
 await expect(page.locator('.progress-stats')).toContainText('35 сек')
 await goTab(page,'Настройки')
 await page.getByRole('button',{name:'Архив и корзина',exact:true}).click()
 const trash=page.getByRole('heading',{name:'Архив и корзина'}).locator('..')
 const sessionRow=trash.locator('.manage-row').filter({hasText:'Тест секунд'})
 await expect(sessionRow).toContainText('В архиве')
 await sessionRow.getByRole('button',{name:'В корзину',exact:true}).click();await page.getByRole('button',{name:'Переместить',exact:true}).click();await expect(sessionRow).toContainText('В корзине')
 await goTab(page,'Прогресс');await expect(page.getByRole('heading',{name:'Прогресс появится после тренировки'})).toBeVisible()
 await goTab(page,'Настройки')
 const archiveMenu=page.getByRole('button',{name:'Архив и корзина',exact:true})
 if(await archiveMenu.isVisible())await archiveMenu.click()
 await sessionRow.getByRole('button',{name:'Восстановить',exact:true}).click()
 await goTab(page,'Прогресс');await page.getByLabel('Сторона для сравнения').selectOption('right');await expect(page.locator('.progress-stats')).toContainText('35 сек')
})

test('custom superset can be changed and disabled in the program editor',async({page})=>{
 await page.goto('/training/');await page.getByRole('button',{name:'Создать программу'}).click()
 await page.getByLabel('Название дня',{exact:true}).fill('Круг')
 for(let i=0;i<3;i++){
  if(i)await page.getByRole('button',{name:'Упражнение',exact:true}).click()
  await page.getByLabel('Название и вариант').nth(i).fill('Тест '+(i+1))
  await page.getByLabel('Тренажёр / оборудование').nth(i).fill('Тестовый')
  await editExercise(page,i)
  await page.getByLabel('Группа суперсета').nth(i).fill('A')
 }
 await page.getByRole('button',{name:'Сохранить программу'}).click();await expect(page.getByRole('button',{name:'Изменить программу',exact:true})).toBeVisible()
 await page.reload();await openProgramEditor(page);await editAllExercises(page)
 await expect(page.getByLabel('Группа суперсета').nth(2)).toHaveValue('A')
 await goTab(page,'Сегодня');await startDay(page,/Круг/)
 await expect(page.locator('.exercise').getByRole('heading',{name:'Тест 1',exact:true})).toBeVisible()
 const first=page.locator('.exercise');await first.getByLabel('Вес подхода 1',{exact:true}).fill('10');await first.getByLabel('Повторения подхода 1',{exact:true}).fill('10');await first.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.locator('.exercise').getByRole('heading',{name:'Тест 2',exact:true})).toBeVisible()
 await openProgramEditor(page);await editAllExercises(page);await page.getByLabel('Группа суперсета').nth(1).fill('');await page.getByRole('button',{name:'Сохранить программу'}).click();await expect(page.getByRole('button',{name:'Изменить программу',exact:true})).toBeVisible()
 await goTab(page,'Сегодня');await expect(page.locator('.exercise').getByRole('heading',{name:'Тест 2',exact:true})).toBeVisible()
})
