import { test, expect } from '@playwright/test'
import { finishWorkout, lastExercise, startDay } from './helpers'
test('personal AB stays unselected, imports once and logs only confirmed results',async({page})=>{
 await page.goto('/training/')
 await page.getByRole('button',{name:'Добавить Bro Split в дневник'}).click()
 await page.getByRole('button',{name:'Настройки',exact:true}).click()
 await page.getByRole('button',{name:'Готовые программы',exact:true}).click()
 await page.getByRole('button',{name:'Добавить личный шаблон А/Б'}).click()
 await page.getByRole('button',{name:'Сегодня',exact:true}).click()
 await expect(page.locator('.next-day')).toContainText('Грудь')
 const select=page.getByLabel('Текущая программа');await expect(select.locator('option')).toHaveCount(2)
 await select.selectOption({label:'Гипертрофия — всё тело А/Б'})
 await expect(page.getByRole('button',{name:/Тренировка А.*7 упражнений.*14 подходов/})).toBeVisible()
 await page.reload();await expect(select).toHaveValue('ab140926-0001-4000-8000-000000000001')
 await startDay(page,/Тренировка А.*7 упражнений/);await page.getByRole('button',{name:'Добавить',exact:true}).click()
 await expect(page.getByText('0 из 16 подходов выполнено')).toBeVisible()
 await page.getByRole('button',{name:'Следующее упражнение',exact:true}).click()
 const press=page.locator('.exercise')
 await expect(press.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('')
 await press.getByLabel('Вес подхода 1',{exact:true}).fill('12')
 await press.getByLabel('Повторения подхода 1',{exact:true}).fill('10')
 await press.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.getByText('1 из 16 подходов выполнено')).toBeVisible()
 const core=await lastExercise(page);await expect(core).toContainText('6–8 на каждую сторону');await expect(core.locator('.set-position')).toContainText('Подход 1 из 2')
 await page.reload();await expect(page.getByText('1 из 16 подходов выполнено')).toBeVisible()
 await finishWorkout(page)
 await expect(page.locator('.next-day')).toContainText('Тренировка Б')
})
