import { test, expect, type Page } from '@playwright/test'

async function createProgram(page:Page) {
 await page.goto('/training/')
 await page.getByRole('button',{name:'Создать программу',exact:true}).click()
 await page.getByLabel('Название программы',{exact:true}).fill('Программа UX')
 await page.getByLabel('Название дня',{exact:true}).fill('День UX')
 await page.getByLabel('Название и вариант',{exact:true}).fill('Тестовый жим')
 await page.getByLabel('Тренажёр / оборудование',{exact:true}).fill('Мой тренажёр')
 await page.getByRole('button',{name:'Сохранить программу',exact:true}).click()
 await expect(page.getByRole('button',{name:'Изменить программу',exact:true})).toBeVisible()
}

async function seedHistory(page:Page) {
 await page.goto('/training/')
 const ids=await page.evaluate(async()=>{
  const dataPath='/training/src/data.ts',domainPath='/training/src/domain.ts',progressPath='/training/src/progress.ts'
  const {db}=await import(dataPath),{uid,makeSession,confirmSet}=await import(domainPath),{contextKey}=await import(progressPath)
  const exercise=(name:string)=>({id:uid(),variantId:uid(),equipmentId:uid(),name,equipment:'Тестовый блок',mode:'MachineStack',sets:2,target:'10',rest:90})
  const p={id:uid(),name:'Программа UX',version:1,days:[{id:uid(),name:'День UX',exercises:[exercise('Тестовый жим'),exercise('Тестовая тяга')]}]}
  await db.programs.put(p)
  const sessions=['2026-01-10','2026-04-20','2026-09-10'].map((date,i)=>{
   const session=makeSession(p,p.days[0]);session.localDate=date;session.startedAt=date+'T12:00:00.000Z'
   for(const ex of session.exercises)for(const record of ex.records){record.weight=String(40+i*5);record.reps='10';confirmSet(session,ex.id,record.id)}
   session.status='completed';session.completedAt=date+'T13:00:00.000Z';session.restEndsAt=null;return session
  })
  await db.sessions.bulkPut(sessions)
  return {programId:p.id,equipmentId:p.days[0].exercises[0].equipmentId,sessionId:sessions[2].id,exerciseId:sessions[2].exercises[1].id,setId:sessions[2].exercises[1].records[1].id,context:contextKey(p.days[0].exercises[1])}
 })
 await page.getByRole('button',{name:'Программы',exact:true}).click()
 await expect(page.getByRole('button',{name:'Изменить программу',exact:true})).toBeVisible()
 return ids
}

test('program drafts survive navigation and reload; discard restores saved overview',async({page})=>{
 await createProgram(page)
 await expect(page.getByLabel('Название программы',{exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'Изменить программу',exact:true}).click()
 await page.getByLabel('Название программы',{exact:true}).fill('Ещё не применено')
 await expect(page.locator('.editor-draft-status')).toContainText('Черновик сохранён')
 await page.getByRole('button',{name:'История',exact:true}).click()
 await page.getByRole('button',{name:'Программы',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Программа UX',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Изменить программу',exact:true}).click()
 await expect(page.getByLabel('Название программы',{exact:true})).toHaveValue('Ещё не применено')
 await page.reload()
 await expect(page.getByLabel('Название программы',{exact:true})).toHaveValue('Ещё не применено')
 await page.getByRole('button',{name:'Отменить изменения',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Программа UX',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Изменить программу',exact:true}).click()
 await expect(page.getByLabel('Название программы',{exact:true})).toHaveValue('Программа UX')
})

test('new program draft reloads; added day reveals fields and invalid collapsed fields are focused',async({page})=>{
 await page.goto('/training/');await page.getByRole('button',{name:'Создать программу',exact:true}).click()
 await page.getByLabel('Название программы',{exact:true}).fill('Новый черновик')
 await page.getByLabel('Название дня',{exact:true}).fill('Первый день')
 await page.getByLabel('Название и вариант',{exact:true}).fill('Первое упражнение')
 await page.getByLabel('Тренажёр / оборудование',{exact:true}).fill('Штанга')
 await expect(page.locator('.editor-draft-status')).toContainText('Черновик сохранён')
 await page.reload()
 await expect(page.getByLabel('Название программы',{exact:true})).toHaveValue('Новый черновик')
 await page.getByRole('button',{name:'День',exact:true}).click()
 await expect(page.getByLabel('Название дня',{exact:true}).nth(1)).toBeFocused()
 await page.getByLabel('Название дня',{exact:true}).nth(1).fill('Второй день')
 const second=page.locator('.program-editor .card').nth(1)
 await expect(second.getByLabel('Название и вариант',{exact:true})).toBeVisible()
 await second.getByLabel('Название и вариант',{exact:true}).fill('Тяга')
 await second.locator('.ex-toggle').click()
 await page.getByRole('button',{name:'Сохранить программу',exact:true}).click()
 await expect(second.getByLabel('Тренажёр / оборудование',{exact:false})).toBeVisible()
 await expect(second.locator('input[data-field$=".equipment"]')).toBeFocused()
 await expect(second.getByText('Укажите оборудование или «Собственный вес».',{exact:true})).toBeVisible()
 await second.locator('input[data-field$=".equipment"]').fill('Блок')
 await page.getByRole('button',{name:'Сохранить программу',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Новый черновик',exact:true})).toBeVisible()
})

test('guide search supports choosing a known exercise and a manual name',async({page})=>{
 await createProgram(page);await page.getByRole('button',{name:'Изменить программу',exact:true}).click()
 await page.locator('.ex-toggle').first().click()
 await page.getByRole('button',{name:'Найти в справочнике',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Справочник упражнений'})
 await dialog.getByLabel('Поиск упражнения',{exact:true}).fill('Жим гантелей лёжа')
 await dialog.getByRole('button',{name:/Жим гантелей лёжа/}).click()
 await expect(page.getByLabel('Название и вариант',{exact:true})).toHaveValue('Жим гантелей лёжа')
 await page.getByLabel('Название и вариант',{exact:true}).fill('Моё упражнение')
 await page.getByRole('button',{name:'Сохранить программу',exact:true}).click()
 await expect(page.locator('.program-overview')).toContainText('Моё упражнение')
})

test('cosmetic equipment rename preserves comparison identity and overview stays read-only',async({page})=>{
 const ids=await seedHistory(page)
 await page.getByRole('button',{name:'Изменить программу',exact:true}).click()
 await page.locator('.ex-toggle').first().click()
 await page.getByLabel('Тренажёр / оборудование',{exact:true}).fill('Тестовый блок, исправленное название')
 await page.getByRole('button',{name:'Сохранить программу',exact:true}).click()
 await expect(page.locator('.program-overview')).toContainText('Тестовый блок, исправленное название')
 await expect(page.locator('.program-overview input')).toHaveCount(0)
 const equipmentId=await page.evaluate(async id=>{const path='/training/src/data.ts';const {db}=await import(path);return (await db.programs.get(id)).days[0].exercises[0].equipmentId},ids.programId)
 expect(equipmentId).toBe(ids.equipmentId)
})

test('targeted history correction opens only the chosen set and restores its draft',async({page})=>{
 const ids=await seedHistory(page)
 await page.getByRole('button',{name:'История',exact:true}).click();await page.locator('.history-row').first().click()
 const exercise=page.locator('.workout-history .exercise').filter({has:page.getByRole('heading',{name:'Тестовая тяга',exact:true})})
 await exercise.getByRole('button',{name:'Исправить подход',exact:true}).nth(1).click()
 await expect(page.locator('.workout-history')).toHaveCount(0)
 const editor=page.locator('.history-editor'),target=editor.locator('[data-record="'+ids.setId+'"]')
 await expect(target).toHaveAttribute('open','')
 await expect(editor.locator('.correction-set[open]')).toHaveCount(1)
 await target.getByLabel('Вес, кг',{exact:true}).fill('65')
 await expect(page.locator('.editor-draft-status')).toContainText('Черновик сохранён')
 await page.reload()
 await expect(target.getByLabel('Вес, кг',{exact:true})).toHaveValue('65')
 await page.getByRole('button',{name:'Сохранить исправления',exact:true}).click()
 await expect(page.locator('.history-editor')).toHaveCount(0)
 await expect(exercise.getByLabel('Вес подхода 2',{exact:true})).toHaveValue('65')
 const updated=await page.evaluate(async id=>{const path='/training/src/data.ts';const {db}=await import(path);return await db.sessions.get(id)},ids.sessionId)
 expect(updated.exercises[1].records[1].loadGrams).toBe(65000)
 expect(updated.exercises[1].records[0].loadGrams).toBe(50000)
})

test('progress preserves profile, dates and selected point after linked history and browser Back',async({page})=>{
 const ids=await seedHistory(page)
 await page.getByRole('button',{name:'Прогресс',exact:true}).click()
 await page.getByRole('combobox',{name:'Упражнение и профиль',exact:true}).selectOption(ids.context)
 await page.getByText('Период и выгрузка',{exact:true}).click()
 await page.getByLabel('С даты',{exact:true}).fill('2026-01-01')
 await page.getByLabel('По дату',{exact:true}).fill('2026-09-30')
 await page.getByLabel('Минимум повторений в подходе',{exact:true}).fill('8')
 const point=page.getByRole('combobox',{name:'Точка графика',exact:true}).first()
 await point.selectOption({index:1})
 const selected=await point.inputValue()
 await page.getByRole('button',{name:'Открыть тренировку',exact:true}).first().click()
 await page.getByRole('button',{name:'К прогрессу',exact:true}).click()
 await expect(page.getByRole('combobox',{name:'Упражнение и профиль',exact:true})).toHaveValue(ids.context)
 await expect(point).toHaveValue(selected)
 await page.getByText('Период и выгрузка',{exact:true}).click()
 await expect(page.getByLabel('С даты',{exact:true})).toHaveValue('2026-01-01')
 await expect(page.getByLabel('По дату',{exact:true})).toHaveValue('2026-09-30')
 await page.getByRole('button',{name:'Открыть тренировку',exact:true}).first().click()
 await page.goBack()
 await expect(page.getByLabel('Минимум повторений в подходе',{exact:true})).toHaveValue('8')
 await expect(point).toHaveValue(selected)
 const chart=page.getByRole('group',{name:'Вес по тренировкам',exact:true})
 await chart.locator('[aria-pressed="true"]').focus();await page.keyboard.press('ArrowLeft')
 await expect(point).not.toHaveValue(selected)
 await page.getByRole('button',{name:'3 месяца',exact:true}).click()
 await expect(page.getByRole('button',{name:'3 месяца',exact:true})).toHaveAttribute('aria-pressed','true')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('management and results fit 320px with readable charts and visible editor actions',async({page},info)=>{
 await page.setViewportSize({width:320,height:740})
 await seedHistory(page)
 await page.getByRole('button',{name:'Изменить программу',exact:true}).click()
 await page.locator('.ex-toggle').first().click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:info.outputPath('program-editor-320.png'),fullPage:true})
 await page.getByRole('button',{name:'Отменить изменения',exact:true}).click()
 await page.getByRole('button',{name:'Прогресс',exact:true}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const chart=page.getByRole('group',{name:'Вес по тренировкам',exact:true})
 await expect(chart.locator('text').first()).toBeVisible()
 const target=await chart.locator('.progress-point').first().boundingBox()
 expect(target!.width).toBeGreaterThanOrEqual(44)
 await chart.scrollIntoViewIfNeeded()
 await page.screenshot({path:info.outputPath('progress-320.png'),fullPage:true})
 await page.getByRole('button',{name:'Открыть тренировку',exact:true}).first().click()
 await page.getByRole('button',{name:'Исправить подход',exact:true}).nth(1).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await expect(page.getByRole('button',{name:'Сохранить исправления',exact:true})).toBeVisible()
 await page.screenshot({path:info.outputPath('history-editor-320.png'),fullPage:true})
})
