import { test, expect } from '@playwright/test'
import { finishWorkout, openExercise } from './helpers'
test('source import persists and starts a blank chest workout',async({page})=>{
 await page.goto('/training/')
 await page.getByRole('button',{name:'Добавить Bro Split в дневник'}).click()
 await expect(page.getByRole('button',{name:/Грудь.*5 упражнений/})).toBeVisible()
 await page.reload()
 await expect(page.getByRole('button',{name:'Добавить Bro Split в дневник'})).toHaveCount(0)
 await page.getByRole('button',{name:/Грудь.*5 упражнений/}).click()
 await page.getByRole('button',{name:'Начать тренировку',exact:true}).click()
 await expect(page.getByText('0 из 16 подходов выполнено')).toBeVisible()
 await expect(page.getByLabel('Вес подхода 1',{exact:true}).first()).toHaveValue('')
 await openExercise(page,'Сведение рук в тренажёре «бабочка»')
 await page.getByRole('button',{name:'Как выполнять',exact:true}).click()
 await expect(page.getByText(/D1 · Суперсет с D2/).first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('Russian exercise guide opens two photos on a phone',async({page},testInfo)=>{
 await page.goto('/training/');await page.getByRole('button',{name:'Добавить Bro Split в дневник'}).click()
 await page.getByRole('button',{name:/Грудь.*5 упражнений/}).click()
 await page.getByRole('button',{name:'Начать тренировку',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Жим гантелей на наклонной скамье',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Как выполнять',exact:true}).click()
 const guide=page.locator('.exercise-guide').first()
 const photo=guide.locator('.guide-photo');await expect(photo).toBeVisible()
 await expect.poll(()=>photo.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true)
 const first=await photo.getAttribute('src');await guide.getByRole('button',{name:'Фото 2',exact:true}).click()
 await expect(photo).not.toHaveAttribute('src',first!);await expect.poll(()=>photo.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true)
 await expect(guide).toContainText('В оригинале: Incline Pronated DB Bench Press')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(()=>innerWidth))
 await guide.scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath('exercise-guide.png')})
 await page.getByRole('button',{name:'Закрыть',exact:true}).click();await page.getByLabel('Вес подхода 1',{exact:true}).first().fill('20')
 await page.getByLabel('Повторения подхода 1',{exact:true}).first().fill('10')
 await page.getByRole('button',{name:'Готово',exact:true}).first().click();await expect(page.getByLabel('Вес подхода 2',{exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Обзор тренировки',exact:true})).toContainText('1 из 16 подходов выполнено')
})

test('superset alternates persisted sets and completed workout suggests next day',async({page})=>{
 await page.goto('/training/');await page.getByRole('button',{name:'Добавить Bro Split в дневник'}).click()
 await expect(page.locator('.next-day')).toContainText('Грудь')
 await page.getByRole('button',{name:/Руки.*7 упражнений/}).click()
 await page.getByRole('button',{name:'Начать тренировку',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Французский жим с гантелями лёжа',exact:true})).toBeVisible()
 await expect(page.locator('.set-live')).toHaveCount(1)
 await page.getByLabel('Вес подхода 1',{exact:true}).fill('10');await page.getByLabel('Повторения подхода 1',{exact:true}).fill('10');await page.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Сгибание рук с гантелями на наклонной скамье',exact:true})).toBeVisible()
 await page.getByLabel('Вес подхода 1',{exact:true}).fill('8');await page.getByLabel('Повторения подхода 1',{exact:true}).fill('10');await page.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.locator('.set-position')).toContainText('Подход 2 из 4')
 await page.reload();await expect(page.getByRole('heading',{name:'Французский жим с гантелями лёжа',exact:true})).toBeVisible();await expect(page.locator('.set-position')).toContainText('Подход 2 из 4')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(()=>innerWidth))
 await finishWorkout(page)
 await expect(page.locator('.next-day')).toContainText('Плечи')
 await page.getByRole('button',{name:'Начать предложенный день'}).click()
 await expect(page.getByRole('heading',{name:'Плечи',exact:true})).toBeVisible()
})
