import { test,expect,type Page } from '@playwright/test'

async function workout(page:Page) {
 await page.goto('/training/')
 await page.evaluate(async()=>{
  const dataPath='/training/src/data.ts',domainPath='/training/src/domain.ts',programPath='/training/src/broSplit.ts'
  const {db}=await import(dataPath),{makeSession,emptySet}=await import(domainPath),{broSplit}=await import(programPath)
  const program=structuredClone(broSplit)
  program.name='UX программа';delete program.seedKey
  const session=makeSession(program,program.days[0])
  session.name='UX тренировка';session.exercises=session.exercises.slice(0,2)
  session.exercises.forEach((exercise:{name:string;mode:string;requiresEquipment:boolean;unilateral:boolean;rest:number;records:unknown[]},index:number)=>{
   exercise.name=index?'UX тяга':'UX жим';exercise.mode='MachineStack';exercise.requiresEquipment=false;exercise.unilateral=false;exercise.rest=60
   exercise.records=Array.from({length:3},()=>emptySet())
  })
  session.exercises[0].records[0].weight='72,5';session.exercises[0].records[0].reps='8'
  await db.programs.put(program);await db.sessions.put(session)
 })
 await expect(page.getByRole('heading',{name:'UX жим',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Готово',exact:true})).toBeEnabled()
}

test('one selected set, two-tap overview and selection survive reorder and reload',async({page})=>{
 await workout(page)
 await expect(page.locator('.set-live')).toHaveCount(1)
 await page.getByRole('button',{name:'Обзор тренировки',exact:true}).click()
 await page.locator('.workout-overview section').first().getByRole('button',{name:/Подход 3/}).click()
 await expect(page.getByLabel('Вес подхода 3',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Действия: UX жим',exact:true}).click()
 await page.getByRole('button',{name:'Переместить UX жим ниже',exact:true}).click()
 await expect(page.getByRole('heading',{name:'UX жим',exact:true})).toBeVisible()
 await expect(page.getByLabel('Вес подхода 3',{exact:true})).toBeVisible()
 await page.reload()
 await expect(page.getByLabel('Вес подхода 3',{exact:true})).toBeVisible()
 await expect(page.locator('.set-live')).toHaveCount(1)
})

test('numeric panel replaces the selected value, clears and moves to repetitions',async({page})=>{
 await workout(page)
 await page.getByLabel('Вес подхода 1',{exact:true}).click()
 const pad=page.getByRole('group',{name:'Цифровая панель'})
 await pad.getByRole('button',{name:'8',exact:true}).click()
 await pad.getByRole('button',{name:'0',exact:true}).click()
 await expect(page.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('80')
 await pad.getByRole('button',{name:'К повторениям',exact:true}).click()
 await pad.getByRole('button',{name:'Очистить',exact:true}).click()
 await pad.getByRole('button',{name:'1',exact:true}).click()
 await pad.getByRole('button',{name:'0',exact:true}).click()
 await expect(page.getByLabel('Повторения подхода 1',{exact:true})).toHaveValue('10')
 await expect(page.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('80')
})

test('sheet retains input focus through updates and traps Tab with focus return',async({page})=>{
 await workout(page)
 const opener=page.getByRole('button',{name:'Ещё о подходе 1',exact:true})
 await opener.click()
 const note=page.getByLabel('Заметка',{exact:true})
 await note.click();await note.pressSequentially('Заметка к подходу',{delay:100})
 await expect(note).toBeFocused()
 await page.waitForTimeout(1100)
 await expect(note).toBeFocused()
 await expect(note).toHaveValue('Заметка к подходу')
 await page.getByRole('button',{name:'Пропустить подход',exact:true}).focus()
 await page.keyboard.press('Tab')
 await expect(page.getByRole('button',{name:'Закрыть',exact:true})).toBeFocused()
 await page.keyboard.press('Shift+Tab')
 await expect(page.getByRole('button',{name:'Пропустить подход',exact:true})).toBeFocused()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(opener).toBeFocused()
 const finish=page.getByRole('button',{name:'Завершить тренировку',exact:true})
 await finish.click()
 await expect(page.getByRole('alertdialog')).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('alertdialog')).toHaveCount(0)
 await expect(finish).toBeFocused()
})

test('inline errors focus the field and timer with keypad fits a narrow phone',async({page},info)=>{
 await workout(page)
 await page.getByLabel('Повторения подхода 1',{exact:true}).fill('')
 await page.getByRole('button',{name:'Готово',exact:true}).click()
 const count=page.getByLabel('Повторения подхода 1',{exact:true})
 await expect(count).toHaveAttribute('aria-invalid','true')
 await expect(page.locator('.set-live').getByRole('alert')).toContainText('повторений')
 await expect(count).toBeFocused()
 await page.getByRole('group',{name:'Цифровая панель'}).getByRole('button',{name:'8',exact:true}).click()
 await page.getByRole('button',{name:'Готово',exact:true}).click()
 await expect(page.getByLabel('Вес подхода 2',{exact:true})).toBeVisible()
 await expect(page.getByRole('timer')).toBeVisible()
 await page.setViewportSize({width:320,height:640})
 await page.getByLabel('Вес подхода 2',{exact:true}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const footer=await page.locator('.pad-footer').boundingBox(),confirm=await page.getByRole('button',{name:'Готово',exact:true}).boundingBox()
 expect(confirm!.y).toBeGreaterThanOrEqual(footer!.y+footer!.height)
 await page.getByRole('button',{name:'Скрыть панель',exact:true}).click()
 await expect(page.getByRole('button',{name:'Увеличить отдых на 30 секунд',exact:true})).toBeVisible()
 await page.screenshot({path:info.outputPath('workout-320.png'),fullPage:true})
})
