import { test, expect } from '@playwright/test'
import { editExercise, exerciseMenu, finishWorkout, goTab, openProgramEditor, selectSet, startDay } from './helpers'
async function setup(page: import('@playwright/test').Page) {
 await page.goto('/training/');await page.getByRole('button',{name:'Создать программу',exact:true}).click()
 await page.getByLabel('Название дня',{exact:true}).fill('Тестовый день')
 await page.getByLabel('Название и вариант').fill('Тестовый жим')
 await page.getByLabel('Тренажёр / оборудование').fill('Тестовый Смит')
 await editExercise(page,0);await page.getByLabel('Как учитывать вес').selectOption('SmithPlatesOnly')
 await page.getByRole('button',{name:'Сохранить программу'}).click()
 await expect(page.getByText('Программа сохранена.',{exact:false})).toBeVisible()
 await goTab(page,'Сегодня');await startDay(page,/Тестовый день/)
 await expect(page.getByRole('heading',{name:'Тестовый жим',exact:true})).toBeVisible()
}
test('three sets survive reload, history feeds the next workout, mobile fits',async({page},info)=>{
 await setup(page)
 for(let i=1;i<=3;i++){
  await page.getByLabel(`Вес подхода ${i}`,{exact:true}).fill('72,5')
  await page.getByLabel(`Повторения подхода ${i}`,{exact:true}).fill('8')
  await page.getByRole('button',{name:'Готово',exact:true}).click()
  await expect(page.getByRole('button',{name:'Обзор тренировки'})).toContainText(`${i} из 3 подходов выполнено`)
 }
 await page.reload();await selectSet(page,'Тестовый жим',0)
 await expect(page.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('72,5')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:info.outputPath('workout-mobile.png'),fullPage:true})
 await finishWorkout(page);await goTab(page,'История')
 await page.getByRole('button',{name:/Тестовый день/}).click()
 await expect(page.getByRole('button',{name:'Исправить подход',exact:true})).toHaveCount(3)
 await goTab(page,'Сегодня');await startDay(page,/Тестовый день/)
 await expect(page.locator('.previous')).toContainText('72,5 кг × 8')
 await expect(page.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('72,5')
 await expect(page.getByLabel('Повторения подхода 1',{exact:true})).toHaveValue('8')
})
test('draft persists without becoming completed; second tab is read only',async({page,context})=>{
 await setup(page);await page.getByLabel('Вес подхода 1',{exact:true}).fill('72,')
 // Во время тренировки сообщение только озвучивается, поэтому проверяем его наличие, а не видимость.
 await expect(page.getByText('Черновик сохранён на устройстве',{exact:true})).toBeAttached()
 await page.reload();await expect(page.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('72,')
 await expect(page.getByRole('button',{name:'Обзор тренировки'})).toContainText('0 из 3 подходов выполнено')
 const second=await context.newPage();await second.goto('/training/')
 await expect(second.getByText('Режим чтения.',{exact:false})).toBeVisible()
 await expect(second.getByRole('button',{name:'Готово',exact:true})).toBeDisabled()
})
test('double click does not confirm another set; incomplete finish keeps blank sets skipped',async({page})=>{
 await setup(page)
 await page.getByLabel('Вес подхода 1',{exact:true}).fill('40');await page.getByLabel('Повторения подхода 1',{exact:true}).fill('10')
 await page.getByRole('button',{name:'Готово',exact:true}).dblclick()
 await expect(page.getByRole('button',{name:'Обзор тренировки'})).toContainText('1 из 3 подходов выполнено')
 await finishWorkout(page);await goTab(page,'История');await page.getByRole('button',{name:/Тестовый день/}).click()
 await expect(page.getByText('Пропущен',{exact:true})).toHaveCount(2)
 await expect(page.getByText('1 из 3 подходов выполнено',{exact:false})).toBeVisible()
})
test('history corrections update progress, cancel is inert, CSV downloads',async({page},info)=>{
 await setup(page);await page.getByLabel('Вес подхода 1',{exact:true}).fill('40');await page.getByLabel('Повторения подхода 1',{exact:true}).fill('10')
 await page.getByRole('button',{name:'Готово',exact:true}).click();await finishWorkout(page);await goTab(page,'Прогресс')
 await expect(page.locator('.progress-stats')).toContainText('40 кг')
 await page.getByRole('button',{name:'Открыть тренировку',exact:true}).first().click()
 await page.getByRole('button',{name:'Исправить подход',exact:true}).first().click()
 await page.getByLabel('Вес, кг',{exact:true}).first().fill('75');await page.getByRole('button',{name:'Отменить исправления',exact:true}).click()
 await page.getByRole('button',{name:'Исправить подход',exact:true}).first().click()
 await expect(page.getByLabel('Вес, кг',{exact:true}).first()).toHaveValue('40')
 await page.getByLabel('Вес, кг',{exact:true}).first().fill('72,5');await page.getByRole('button',{name:'Сохранить исправления',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Исправление записи',exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'К прогрессу',exact:true}).click();await expect(page.locator('.progress-stats')).toContainText('72,5 кг')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByText('Период и выгрузка',{exact:true}).click()
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'CSV тренировок за период'}).click()
 expect((await download).suggestedFilename()).toMatch(/\.csv$/)
 await page.reload();await expect(page.locator('.progress-stats')).toContainText('72,5 кг')
 await page.screenshot({path:info.outputPath('progress-mobile.png'),fullPage:true})
})
test('copy and reorder days survive save, touch fields fit phone',async({page})=>{
 await page.goto('/training/');await page.getByRole('button',{name:'Создать программу'}).click()
 await page.getByLabel('Название дня',{exact:true}).fill('Первый')
 await page.getByLabel('Название и вариант').fill('Жим');await page.getByLabel('Тренажёр / оборудование').fill('Смит')
 await page.getByRole('button',{name:'Копировать день'}).click();await page.getByLabel('Название дня',{exact:true}).nth(1).fill('Второй')
 await page.getByRole('button',{name:'День 2 выше',exact:true}).click()
 const field=page.getByLabel('Название дня',{exact:true}).first();await expect(field).toHaveValue('Второй')
 expect(await field.evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(16)
 expect((await field.boundingBox())!.height).toBeGreaterThanOrEqual(44)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Сохранить программу'}).click();await expect(page.getByText('Программа сохранена.',{exact:false})).toBeVisible()
 await page.reload();await openProgramEditor(page);await expect(page.getByLabel('Название дня',{exact:true}).first()).toHaveValue('Второй')
 await goTab(page,'Сегодня');await startDay(page,/Второй.*1 упражнений/)
 await expect(page.getByRole('heading',{name:'Жим',exact:true})).toBeVisible()
})
test('swap preserves drafts and reordering keeps selection attached to exercise',async({page},info)=>{
 await setup(page);await page.getByLabel('Вес подхода 1',{exact:true}).fill('72,')
 await exerciseMenu(page,'Тестовый жим');await page.getByRole('button',{name:'Заменить на сегодня',exact:true}).click()
 await page.getByLabel('Название замены').fill('Тяга на сегодня');await page.getByLabel('Оборудование замены').fill('Блок');await page.getByLabel('Учёт веса замены').selectOption('MachineStack')
 await page.getByRole('button',{name:'Добавить замену рядом'}).click()
 const shown=page.locator('.exercise');await expect(shown.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('72,')
 await selectSet(page,'Тяга на сегодня',0);await expect(shown.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('')
 await shown.getByLabel('Вес подхода 1',{exact:true}).fill('25');await shown.getByLabel('Повторения подхода 1',{exact:true}).fill('12');await shown.getByRole('button',{name:'Готово',exact:true}).click()
 await selectSet(page,'Тяга на сегодня',0);await exerciseMenu(page,'Тяга на сегодня')
 await page.getByRole('button',{name:'Переместить Тяга на сегодня выше',exact:true}).click()
 await expect(shown.getByRole('heading',{name:'Тяга на сегодня',exact:true})).toBeVisible()
 await page.reload();await expect(shown.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('25')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:info.outputPath('iphone-workout.png'),fullPage:true})
 await selectSet(page,'Тестовый жим',0);await expect(shown.getByLabel('Вес подхода 1',{exact:true})).toHaveValue('72,')
 await page.setViewportSize({width:956,height:440});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await expect(page.getByRole('navigation')).toHaveCount(0)
 await selectSet(page,'Тестовый жим',1);await page.getByLabel('Повторения подхода 2',{exact:true}).fill('8')
 await openProgramEditor(page);await editExercise(page,0)
 await expect(page.getByLabel('Название и вариант')).toHaveCount(1);await expect(page.getByLabel('Название и вариант')).toHaveValue('Тестовый жим')
})
